---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-clientes
  labels:
    app: api-clientes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-clientes
  template:
    metadata:
      labels:
        app: api-clientes
    spec:
      containers:
        - name: api-clientes-container
          image: viniciusdep/api-clientes-prom
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-api-clientes
spec:
  selector:
    app: api-clientes
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000