---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-produtos
  labels:
    app: api-produtos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-produtos
  template:
    metadata:
      labels:
        app: api-produtos
    spec:
      containers:
        - name: api-produtos-container
          image: viniciusdep/api-produtos-prom
          ports:
            - containerPort: 5200
---
#Cluster IP catalogo
apiVersion: v1
kind: Service
metadata:
  name: svc-api-produtos
spec:
  selector:
    app: api-produtos
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5200

